name: The Wee House
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5267219441011548
title: 'The Wee House '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#ffffff'
    - '#94aebb'
    - '#5e5c5f'
    - '#ff4d22'
  brandStrength: 0.7987344022840261
  lightness: 0.18142255232669413
  saturation: 0.3125
  rhythmicContrast: 0.31750122737139463
purpose: []
